drop table if exists Song;
create table Song (id varchar(255) not null, name varchar(255), primary key (id)) type=MyISAM;
drop table if exists song;
create table song (id varchar(255) not null, name varchar(255), primary key (id)) type=MyISAM;
drop table if exists song;
drop table if exists uuid;
create table song (id varchar(255) not null, name varchar(255), primary key (id)) type=MyISAM;
create table uuid (next_val bigint) type=MyISAM;
insert into uuid values ( 1 );
drop table if exists song;
drop table if exists uuid;
create table song (id varchar(255) not null, name varchar(255), primary key (id)) type=MyISAM;
create table uuid (next_val bigint) type=MyISAM;
insert into uuid values ( 1 );
