package org.fluentness.common.constants;

public interface SettingKeys {

    SettingKeys.Key APP_PROTOCOL = Key.APP_PROTOCOL;
    SettingKeys.Key APP_HOST = Key.APP_HOST;
    SettingKeys.Key APP_PORT = Key.APP_PORT;
    SettingKeys.Key APP_KEYSTORE = Key.APP_KEYSTORE;
    SettingKeys.Key HIBERNATE_DRIVER = Key.HIBERNATE_DRIVER;
    SettingKeys.Key HIBERNATE_DRIVER_CLASS = Key.HIBERNATE_DRIVER_CLASS;
    SettingKeys.Key HIBERNATE_HOST = Key.HIBERNATE_HOST;
    SettingKeys.Key HIBERNATE_PORT = Key.HIBERNATE_PORT;
    SettingKeys.Key HIBERNATE_DATABASE = Key.HIBERNATE_DATABASE;
    SettingKeys.Key HIBERNATE_USERNAME = Key.HIBERNATE_USERNAME;
    SettingKeys.Key HIBERNATE_PASSWORD = Key.HIBERNATE_PASSWORD;
    SettingKeys.Key HIBERNATE_PARAMS = Key.HIBERNATE_PARAMS;
    SettingKeys.Key HIBERNATE_DIALECT = Key.HIBERNATE_DIALECT;
    SettingKeys.Key HIBERNATE_OPTIONS = Key.HIBERNATE_OPTIONS;
    SettingKeys.Key LOG_LEVEL = Key.LOG_LEVEL;
    SettingKeys.Key ENABLE_CACHE = Key.ENABLE_CACHE;
    SettingKeys.Key ENABLE_HIBERNATE = Key.ENABLE_HIBERNATE;
    SettingKeys.Key ENABLE_LOG_VERBOSE = Key.ENABLE_LOG_VERBOSE;
    SettingKeys.Key ENABLE_LOG_TO_CONSOLE = Key.ENABLE_LOG_TO_CONSOLE;
    SettingKeys.Key ENABLE_LOG_TO_FILE = Key.ENABLE_LOG_TO_FILE;
    SettingKeys.Key ENABLE_STYLE_MINIFY = Key.ENABLE_STYLE_MINIFY;

    enum Key {
        APP_PROTOCOL,
        APP_HOST,
        APP_PORT,
        APP_KEYSTORE,
        HIBERNATE_DRIVER,
        HIBERNATE_DRIVER_CLASS,
        HIBERNATE_HOST,
        HIBERNATE_PORT,
        HIBERNATE_DATABASE,
        HIBERNATE_USERNAME,
        HIBERNATE_PASSWORD,
        HIBERNATE_PARAMS,
        HIBERNATE_DIALECT,
        HIBERNATE_OPTIONS,
        LOG_LEVEL,
        ENABLE_CACHE,
        ENABLE_HIBERNATE,
        ENABLE_LOG_VERBOSE,
        ENABLE_LOG_TO_CONSOLE,
        ENABLE_LOG_TO_FILE,
        ENABLE_STYLE_MINIFY
    }

}
