package org.fluentness.base.service.localization;

public enum Language {

    AF("Afrikaans"),
    AR("Arabic"),
    AZ("Azeri (Latin)"),
    BE("Belarusian"),
    BG("Bulgarian"),
    CA("Catalan"),
    CS("Czech"),
    CY("Welsh"),
    DA("Danish"),
    DE("German"),
    DV("Divehi"),
    EL("Greek"),
    EN("English"),
    EO("Esperanto"),
    ES("Spanish"),
    ET("Estonian"),
    EU("Basque"),
    FA("Farsi"),
    FI("Finnish"),
    FO("Faroese"),
    FR("French"),
    GL("Galician"),
    GU("Gujarati"),
    HE("Hebrew"),
    HI("Hindi"),
    HR("Croatian"),
    HU("Hungarian"),
    HY("Armenian"),
    ID("Indonesian"),
    IS("Icelandic"),
    IT("Italian"),
    JA("Japanese"),
    KA("Georgian"),
    KK("Kazakh"),
    KN("Kannada"),
    KO("Korean"),
    KY("Kyrgyz"),
    LT("Lithuanian"),
    LV("Latvian"),
    MI("Maori"),
    MK("FYRO Macedonian"),
    MN("Mongolian"),
    MR("Marathi"),
    MS("Malay"),
    MT("Maltese"),
    NB("Norwegian"),
    NL("Dutch"),
    NS("Northern Sotho"),
    PA("Punjabi"),
    PL("Polish"),
    PS("Pashto"),
    PT("Portuguese"),
    QU("Quechua"),
    RO("Romanian"),
    RU("Russian"),
    SA("Sanskrit"),
    SE("Sami"),
    SK("Slovak"),
    SL("Slovenian"),
    SQ("Albanian"),
    SV("Swedish"),
    SW("Swahili"),
    TA("Tamil"),
    TE("Telugu"),
    TH("Thai"),
    TL("Tagalog"),
    TN("Tswana"),
    TR("Turkish"),
    TT("Tatar"),
    TS("Tsonga"),
    UK("Ukrainian"),
    UR("Urdu"),
    UZ("Uzbek (Latin)"),
    VI("Vietnamese"),
    XH("Xhosa"),
    ZH("Chinese"),
    ZU("Zulu");

    private String fullName;

    Language(String fullName) {
        this.fullName = fullName;
    }

    @Override
    public String toString() {
        return fullName;
    }
}
