package org.fluentness.templating;

public class HtmlAttribute {

    private HtmlAttribute() {
    }

    public static DomAttribute accept(String value) { return new DomAttribute("accept",value); }
    public static DomAttribute accept_charset(String value) { return new DomAttribute("accept_charset",value); }
    public static DomAttribute accesskey(String value) { return new DomAttribute("accesskey",value); }
    public static DomAttribute action(String value) { return new DomAttribute("action",value); }
    public static DomAttribute align(String value) { return new DomAttribute("align",value); }
    public static DomAttribute alt(String value) { return new DomAttribute("alt",value); }
    public static DomAttribute async(String value) { return new DomAttribute("async",value); }
    public static DomAttribute autocomplete(String value) { return new DomAttribute("autocomplete",value); }
    public static DomAttribute autofocus(String value) { return new DomAttribute("autofocus",value); }
    public static DomAttribute autoplay(String value) { return new DomAttribute("autoplay",value); }
    public static DomAttribute autosave(String value) { return new DomAttribute("autosave",value); }
    public static DomAttribute border(String value) { return new DomAttribute("border",value); }
    public static DomAttribute buffered(String value) { return new DomAttribute("buffered",value); }
    public static DomAttribute challenge(String value) { return new DomAttribute("challenge",value); }
    public static DomAttribute charset(String value) { return new DomAttribute("charset",value); }
    public static DomAttribute checked(String value) { return new DomAttribute("checked",value); }
    public static DomAttribute cite(String value) { return new DomAttribute("cite",value); }
    public static DomAttribute classs(String value) { return new DomAttribute("class",value); }
    public static DomAttribute color(String value) { return new DomAttribute("color",value); }
    public static DomAttribute cols(String value) { return new DomAttribute("cols",value); }
    public static DomAttribute colspan(String value) { return new DomAttribute("colspan",value); }
    public static DomAttribute content(String value) { return new DomAttribute("content",value); }
    public static DomAttribute contenteditable(String value) { return new DomAttribute("contenteditable",value); }
    public static DomAttribute contextmenu(String value) { return new DomAttribute("contextmenu",value); }
    public static DomAttribute controls(String value) { return new DomAttribute("controls",value); }
    public static DomAttribute coords(String value) { return new DomAttribute("coords",value); }
    public static DomAttribute data(String value) { return new DomAttribute("data",value); }
    public static DomAttribute datetime(String value) { return new DomAttribute("datetime",value); }
    public static DomAttribute defaultt(String value) { return new DomAttribute("default",value); }
    public static DomAttribute defer(String value) { return new DomAttribute("defer",value); }
    public static DomAttribute dir(String value) { return new DomAttribute("dir",value); }
    public static DomAttribute dirname(String value) { return new DomAttribute("dirname",value); }
    public static DomAttribute disabled(String value) { return new DomAttribute("disabled",value); }
    public static DomAttribute download(String value) { return new DomAttribute("download",value); }
    public static DomAttribute draggable(String value) { return new DomAttribute("draggable",value); }
    public static DomAttribute dropzone(String value) { return new DomAttribute("dropzone",value); }
    public static DomAttribute enctype(String value) { return new DomAttribute("enctype",value); }
    public static DomAttribute forr(String value) { return new DomAttribute("for",value); }
    public static DomAttribute form(String value) { return new DomAttribute("form",value); }
    public static DomAttribute formaction(String value) { return new DomAttribute("formaction",value); }
    public static DomAttribute headers(String value) { return new DomAttribute("headers",value); }
    public static DomAttribute height(String value) { return new DomAttribute("height",value); }
    public static DomAttribute hidden(String value) { return new DomAttribute("hidden",value); }
    public static DomAttribute high(String value) { return new DomAttribute("high",value); }
    public static DomAttribute href(String value) { return new DomAttribute("href",value); }
    public static DomAttribute hreflang(String value) { return new DomAttribute("hreflang",value); }
    public static DomAttribute http_equiv(String value) { return new DomAttribute("http_equiv",value); }
    public static DomAttribute icon(String value) { return new DomAttribute("icon",value); }
    public static DomAttribute id(String value) { return new DomAttribute("id",value); }
    public static DomAttribute ismap(String value) { return new DomAttribute("ismap",value); }
    public static DomAttribute itemprop(String value) { return new DomAttribute("itemprop",value); }
    public static DomAttribute keytype(String value) { return new DomAttribute("keytype",value); }
    public static DomAttribute kind(String value) { return new DomAttribute("kind",value); }
    public static DomAttribute label(String value) { return new DomAttribute("label",value); }
    public static DomAttribute lang(String value) { return new DomAttribute("lang",value); }
    public static DomAttribute language(String value) { return new DomAttribute("language",value); }
    public static DomAttribute list(String value) { return new DomAttribute("list",value); }
    public static DomAttribute loop(String value) { return new DomAttribute("loop",value); }
    public static DomAttribute low(String value) { return new DomAttribute("low",value); }
    public static DomAttribute manifest(String value) { return new DomAttribute("manifest",value); }
    public static DomAttribute max(String value) { return new DomAttribute("max",value); }
    public static DomAttribute maxlength(String value) { return new DomAttribute("maxlength",value); }
    public static DomAttribute media(String value) { return new DomAttribute("media",value); }
    public static DomAttribute method(String value) { return new DomAttribute("method",value); }
    public static DomAttribute min(String value) { return new DomAttribute("min",value); }
    public static DomAttribute multiple(String value) { return new DomAttribute("multiple",value); }
    public static DomAttribute name(String value) { return new DomAttribute("name",value); }
    public static DomAttribute novalidate(String value) { return new DomAttribute("novalidate",value); }
    public static DomAttribute open(String value) { return new DomAttribute("open",value); }
    public static DomAttribute optimum(String value) { return new DomAttribute("optimum",value); }
    public static DomAttribute pattern(String value) { return new DomAttribute("pattern",value); }
    public static DomAttribute ping(String value) { return new DomAttribute("ping",value); }
    public static DomAttribute placeholder(String value) { return new DomAttribute("placeholder",value); }
    public static DomAttribute poster(String value) { return new DomAttribute("poster",value); }
    public static DomAttribute preload(String value) { return new DomAttribute("preload",value); }
    public static DomAttribute pubdate(String value) { return new DomAttribute("pubdate",value); }
    public static DomAttribute radiogroup(String value) { return new DomAttribute("radiogroup",value); }
    public static DomAttribute readonly(String value) { return new DomAttribute("readonly",value); }
    public static DomAttribute rel(String value) { return new DomAttribute("rel",value); }
    public static DomAttribute required(String value) { return new DomAttribute("required",value); }
    public static DomAttribute reversed(String value) { return new DomAttribute("reversed",value); }
    public static DomAttribute role(String value) { return new DomAttribute("role",value); }
    public static DomAttribute rows(String value) { return new DomAttribute("rows",value); }
    public static DomAttribute rowspan(String value) { return new DomAttribute("rowspan",value); }
    public static DomAttribute sandbox(String value) { return new DomAttribute("sandbox",value); }
    public static DomAttribute scope(String value) { return new DomAttribute("scope",value); }
    public static DomAttribute scoped(String value) { return new DomAttribute("scoped",value); }
    public static DomAttribute seamless(String value) { return new DomAttribute("seamless",value); }
    public static DomAttribute selected(String value) { return new DomAttribute("selected",value); }
    public static DomAttribute shape(String value) { return new DomAttribute("shape",value); }
    public static DomAttribute size(String value) { return new DomAttribute("size",value); }
    public static DomAttribute sizes(String value) { return new DomAttribute("sizes",value); }
    public static DomAttribute span(String value) { return new DomAttribute("span",value); }
    public static DomAttribute spellcheck(String value) { return new DomAttribute("spellcheck",value); }
    public static DomAttribute src(String value) { return new DomAttribute("src",value); }
    public static DomAttribute srcdoc(String value) { return new DomAttribute("srcdoc",value); }
    public static DomAttribute srclang(String value) { return new DomAttribute("srclang",value); }
    public static DomAttribute srcset(String value) { return new DomAttribute("srcset",value); }
    public static DomAttribute start(String value) { return new DomAttribute("start",value); }
    public static DomAttribute step(String value) { return new DomAttribute("step",value); }
    public static DomAttribute style(String value) { return new DomAttribute("style",value); }
    public static DomAttribute summary(String value) { return new DomAttribute("summary",value); }
    public static DomAttribute tabindex(String value) { return new DomAttribute("tabindex",value); }
    public static DomAttribute target(String value) { return new DomAttribute("target",value); }
    public static DomAttribute title(String value) { return new DomAttribute("title",value); }
    public static DomAttribute type(String value) { return new DomAttribute("type",value); }
    public static DomAttribute usemap(String value) { return new DomAttribute("usemap",value); }
    public static DomAttribute value(String value) { return new DomAttribute("value",value); }
    public static DomAttribute width(String value) { return new DomAttribute("width",value); }
    public static DomAttribute wrap(String value) { return new DomAttribute("wrap",value); }

}
