package org.fluentness.service.translator;

public enum Language {

    AF("Afrikaans"),
    AF_ZA("Afrikaans (South Africa)"),
    AR("Arabic"),
    AR_AE("Arabic (U.A.E.)"),
    AR_BH("Arabic (Bahrain)"),
    AR_DZ("Arabic (Algeria)"),
    AR_EG("Arabic (Egypt)"),
    AR_IQ("Arabic (Iraq)"),
    AR_JO("Arabic (Jordan)"),
    AR_KW("Arabic (Kuwait)"),
    AR_LB("Arabic (Lebanon)"),
    AR_LY("Arabic (Libya)"),
    AR_MA("Arabic (Morocco)"),
    AR_OM("Arabic (Oman)"),
    AR_QA("Arabic (Qatar)"),
    AR_SA("Arabic (Saudi Arabia)"),
    AR_SY("Arabic (Syria)"),
    AR_TN("Arabic (Tunisia)"),
    AR_YE("Arabic (Yemen)"),
    AZ("Azeri (Latin)"),
    AZ_AZ("Azeri (Azerbaijan)"),
    BE("Belarusian"),
    BE_BY("Belarusian (Belarus)"),
    BG("Bulgarian"),
    BG_BG("Bulgarian (Bulgaria)"),
    BS_BA("Bosnian (Bosnia and Herzegovina)"),
    CA("Catalan"),
    CA_ES("Catalan (Spain)"),
    CS("Czech"),
    CS_CZ("Czech (Czech Republic)"),
    CY("Welsh"),
    CY_GB("Welsh (United Kingdom)"),
    DA("Danish"),
    DA_DK("Danish (Denmark)"),
    DE("German"),
    DE_AT("German (Austria)"),
    DE_CH("German (Switzerland)"),
    DE_DE("German (Germany)"),
    DE_LI("German (Liechtenstein)"),
    DE_LU("German (Luxembourg)"),
    DV("Divehi"),
    DV_MV("Divehi (Maldives)"),
    EL("Greek"),
    EL_GR("Greek (Greece)"),
    EN("English"),
    EN_AU("English (Australia)"),
    EN_BZ("English (Belize)"),
    EN_CA("English (Canada)"),
    EN_CB("English (Caribbean)"),
    EN_GB("English (United Kingdom)"),
    EN_IE("English (Ireland)"),
    EN_JM("English (Jamaica)"),
    EN_NZ("English (New Zealand)"),
    EN_PH("English (Republic of the Philippines)"),
    EN_TT("English (Trinidad and Tobago)"),
    EN_US("English (United States)"),
    EN_ZA("English (South Africa)"),
    EN_ZW("English (Zimbabwe)"),
    EO("Esperanto"),
    ES("Spanish"),
    ES_AR("Spanish (Argentina)"),
    ES_BO("Spanish (Bolivia)"),
    ES_CL("Spanish (Chile)"),
    ES_CO("Spanish (Colombia)"),
    ES_CR("Spanish (Costa Rica)"),
    ES_DO("Spanish (Dominican Republic)"),
    ES_EC("Spanish (Ecuador)"),
    ES_ES("Spanish (Spain)"),
    ES_GT("Spanish (Guatemala)"),
    ES_HN("Spanish (Honduras)"),
    ES_MX("Spanish (Mexico)"),
    ES_NI("Spanish (Nicaragua)"),
    ES_PA("Spanish (Panama)"),
    ES_PE("Spanish (Peru)"),
    ES_PR("Spanish (Puerto Rico)"),
    ES_PY("Spanish (Paraguay)"),
    ES_SV("Spanish (El Salvador)"),
    ES_UY("Spanish (Uruguay)"),
    ES_VE("Spanish (Venezuela)"),
    ET("Estonian"),
    ET_EE("Estonian (Estonia)"),
    EU("Basque"),
    EU_ES("Basque (Spain)"),
    FA("Farsi"),
    FA_IR("Farsi (Iran)"),
    FI("Finnish"),
    FI_FI("Finnish (Finland)"),
    FO("Faroese"),
    FO_FO("Faroese (Faroe Islands)"),
    FR("French"),
    FR_BE("French (Belgium)"),
    FR_CA("French (Canada)"),
    FR_CH("French (Switzerland)"),
    FR_FR("French (France)"),
    FR_LU("French (Luxembourg)"),
    FR_MC("French (Principality of Monaco)"),
    GL("Galician"),
    GL_ES("Galician (Spain)"),
    GU("Gujarati"),
    GU_IN("Gujarati (India)"),
    HE("Hebrew"),
    HE_IL("Hebrew (Israel)"),
    HI("Hindi"),
    HI_IN("Hindi (India)"),
    HR("Croatian"),
    HR_BA("Croatian (Bosnia and Herzegovina)"),
    HR_HR("Croatian (Croatia)"),
    HU("Hungarian"),
    HU_HU("Hungarian (Hungary)"),
    HY("Armenian"),
    HY_AM("Armenian (Armenia)"),
    ID("Indonesian"),
    ID_ID("Indonesian (Indonesia)"),
    IS("Icelandic"),
    IS_IS("Icelandic (Iceland)"),
    IT("Italian"),
    IT_CH("Italian (Switzerland)"),
    IT_IT("Italian (Italy)"),
    JA("Japanese"),
    JA_JP("Japanese (Japan)"),
    KA("Georgian"),
    KA_GE("Georgian (Georgia)"),
    KK("Kazakh"),
    KK_KZ("Kazakh (Kazakhstan)"),
    KN("Kannada"),
    KN_IN("Kannada (India)"),
    KO("Korean"),
    KO_KR("Korean (Korea)"),
    KOK("Konkani"),
    KOK_IN("Konkani (India)"),
    KY("Kyrgyz"),
    KY_KG("Kyrgyz (Kyrgyzstan)"),
    LT("Lithuanian"),
    LT_LT("Lithuanian (Lithuania)"),
    LV("Latvian"),
    LV_LV("Latvian (Latvia)"),
    MI("Maori"),
    MI_NZ("Maori (New Zealand)"),
    MK("FYRO Macedonian"),
    MK_MK("FYRO Macedonian (Former Yugoslav Republic of Macedonia)"),
    MN("Mongolian"),
    MN_MN("Mongolian (Mongolia)"),
    MR("Marathi"),
    MR_IN("Marathi (India)"),
    MS("Malay"),
    MS_BN("Malay (Brunei Darussalam)"),
    MS_MY("Malay (Malaysia)"),
    MT("Maltese"),
    MT_MT("Maltese (Malta)"),
    NB("Norwegian (Bokm?l)"),
    NB_NO("Norwegian (Bokm?l) (Norway)"),
    NL("Dutch"),
    NL_BE("Dutch (Belgium)"),
    NL_NL("Dutch (Netherlands)"),
    NN_NO("Norwegian (Nynorsk) (Norway)"),
    NS("Northern Sotho"),
    NS_ZA("Northern Sotho (South Africa)"),
    PA("Punjabi"),
    PA_IN("Punjabi (India)"),
    PL("Polish"),
    PL_PL("Polish (Poland)"),
    PS("Pashto"),
    PS_AR("Pashto (Afghanistan)"),
    PT("Portuguese"),
    PT_BR("Portuguese (Brazil)"),
    PT_PT("Portuguese (Portugal)"),
    QU("Quechua"),
    QU_BO("Quechua (Bolivia)"),
    QU_EC("Quechua (Ecuador)"),
    QU_PE("Quechua (Peru)"),
    RO("Romanian"),
    RO_RO("Romanian (Romania)"),
    RU("Russian"),
    RU_RU("Russian (Russia)"),
    SA("Sanskrit"),
    SA_IN("Sanskrit (India)"),
    SE("Sami (Northern)"),
    SE_FI("Sami (Finland)"),
    SE_NO("Sami (Norway)"),
    SE_SE("Sami (Sweden)"),
    SK("Slovak"),
    SK_SK("Slovak (Slovakia)"),
    SL("Slovenian"),
    SL_SI("Slovenian (Slovenia)"),
    SQ("Albanian"),
    SQ_AL("Albanian (Albania)"),
    SR_BA("Serbian (Bosnia and Herzegovina)"),
    SR_SP("Serbian (Serbia and Montenegro)"),
    SV("Swedish"),
    SV_FI("Swedish (Finland)"),
    SV_SE("Swedish (Sweden)"),
    SW("Swahili"),
    SW_KE("Swahili (Kenya)"),
    SYR("Syriac"),
    SYR_SY("Syriac (Syria)"),
    TA("Tamil"),
    TA_IN("Tamil (India)"),
    TE("Telugu"),
    TE_IN("Telugu (India)"),
    TH("Thai"),
    TH_TH("Thai (Thailand)"),
    TL("Tagalog"),
    TL_PH("Tagalog (Philippines)"),
    TN("Tswana"),
    TN_ZA("Tswana (South Africa)"),
    TR("Turkish"),
    TR_TR("Turkish (Turkey)"),
    TT("Tatar"),
    TT_RU("Tatar (Russia)"),
    TS("Tsonga"),
    UK("Ukrainian"),
    UK_UA("Ukrainian (Ukraine)"),
    UR("Urdu"),
    UR_PK("Urdu (Islamic Republic of Pakistan)"),
    UZ("Uzbek (Latin)"),
    UZ_UZ("Uzbek (Uzbekistan)"),
    VI("Vietnamese"),
    VI_VN("Vietnamese (Viet Nam)"),
    XH("Xhosa"),
    XH_ZA("Xhosa (South Africa)"),
    ZH("Chinese"),
    ZH_CN("Chinese (S)"),
    ZH_HK("Chinese (Hong Kong)"),
    ZH_MO("Chinese (Macau)"),
    ZH_SG("Chinese (Singapore)"),
    ZH_TW("Chinese (T)"),
    ZU("Zulu"),
    ZU_ZA("Zulu (South Africa)");

    private final String name;

    Language(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return name;
    }
}
