package org.fwf.tpl;

public class HtmlTag {
    public static final String doctype = "<!DOCTYPE>"; // 	Defines the document type
    public static final String a = "a"; // Defines a hyperlink
    public static final String abbr = "abbr"; // Defines an abbreviation or an acronym
    public static final String acronym = "acronym"; // Not supported in HTML5. Use --abbr-- instead. Defines an acronym
    public static final String address = "address"; // Defines contact information for the author/owner of a document
    public static final String applet = "applet"; // Not supported in HTML5. Use --embed-- or --object-- instead. Defines an embedded applet
    public static final String area = "area"; // Defines an area inside an image-map
    public static final String article = "article"; // Defines an article
    public static final String aside = "aside"; // Defines content aside from the page content
    public static final String audio = "audio"; // Defines sound content
    public static final String b = "b"; // Defines bold text
    public static final String base = "base"; // Specifies the base URL/target for all relative URLs in a document
    public static final String basefont = "basefont"; // Not supported in HTML5. Use CSS instead. Specifies a default color, size, and font for all text in a document
    public static final String bdi = "bdi"; // Isolates a part of text that might be formatted in a different direction from other text outside it
    public static final String bdo = "bdo"; // Overrides the current text direction
    public static final String big = "big"; // Not supported in HTML5. Use CSS instead. Defines big text
    public static final String blockquote = "blockquote"; // Defines a section that is quoted from another source
    public static final String body = "body"; // Defines the document's body
    public static final String br = "br"; // Defines a single line break
    public static final String button = "button"; // Defines a clickable button
    public static final String canvas = "canvas"; // Used to draw graphics, on the fly, via scripting (usually JavaScript)
    public static final String caption = "caption"; // Defines a table caption
    public static final String center = "center"; // Not supported in HTML5. Use CSS instead. Defines centered text
    public static final String cite = "cite"; // Defines the title of a work
    public static final String code = "code"; // Defines a piece of computer code
    public static final String col = "col"; // Specifies column properties for each column within a --colgroup-- element
    public static final String colgroup = "colgroup"; // Specifies a group of one or more columns in a table for formatting
    public static final String data = "data"; // Links the given content with a machine-readable translation
    public static final String datalist = "datalist"; // Specifies a list of pre-defined options for input controls
    public static final String dd = "dd"; // Defines a description/value of a term in a description list
    public static final String del = "del"; // Defines text that has been deleted from a document
    public static final String details = "details"; // Defines additional details that the user can view or hide
    public static final String dfn = "dfn"; // Represents the defining instance of a term
    public static final String dialog = "dialog"; // Defines a dialog box or window
    public static final String dir = "dir"; // Not supported in HTML5. Use --ul-- instead. Defines a directory list
    public static final String div = "div"; // Defines a section in a document
    public static final String dl = "dl"; // Defines a description list
    public static final String dt = "dt"; // Defines a term/name in a description list
    public static final String em = "em"; // Defines emphasized text
    public static final String embed = "embed"; // Defines a container for an external (non-HTML) application
    public static final String fieldset = "fieldset"; // Groups related elements in a form
    public static final String figcaption = "figcaption"; // Defines a caption for a --figure-- element
    public static final String figure = "figure"; // Specifies self-contained content
    public static final String font = "font"; // Not supported in HTML5. Use CSS instead. Defines font, color, and size for text
    public static final String footer = "footer"; // Defines a footer for a document or section
    public static final String form = "form"; // Defines an HTML form for user input
    public static final String frame = "frame"; // Not supported in HTML5. Defines a window (a frame) in a frameset
    public static final String frameset = "frameset"; // Not supported in HTML5. Defines a set of frames
    public static final String h1 = "h1"; // to public static final String h6 = "h6"; // Defines HTML headings
    public static final String head = "head"; // Defines information about the document
    public static final String header = "header"; // Defines a header for a document or section
    public static final String hr = "hr"; // Defines a thematic change in the content
    public static final String html = "html"; // Defines the root of an HTML document
    public static final String i = "i"; // Defines a part of text in an alternate voice or mood
    public static final String iframe = "iframe"; // Defines an inline frame
    public static final String img = "img"; // Defines an image
    public static final String input = "input"; // Defines an input control
    public static final String ins = "ins"; // Defines a text that has been inserted into a document
    public static final String kbd = "kbd"; // Defines keyboard input
    public static final String label = "label"; // Defines a label for an --input-- element
    public static final String legend = "legend"; // Defines a caption for a --fieldset-- element
    public static final String li = "li"; // Defines a list item
    public static final String link = "link"; // Defines the relationship between a document and an external resource (most used to link to style sheets)
    public static final String main = "main"; // Specifies the main content of a document
    public static final String map = "map"; // Defines a client-side image-map
    public static final String mark = "mark"; // Defines marked/highlighted text
    public static final String meta = "meta"; // Defines metadata about an HTML document
    public static final String meter = "meter"; // Defines a scalar measurement within a known range (a gauge)
    public static final String nav = "nav"; // Defines navigation links
    public static final String noframes = "noframes"; // Not supported in HTML5. Defines an alternate content for users that do not support frames
    public static final String noscript = "noscript"; // Defines an alternate content for users that do not support client-side scripts
    public static final String object = "object"; // Defines an embedded object
    public static final String ol = "ol"; // Defines an ordered list
    public static final String optgroup = "optgroup"; // Defines a group of related options in a drop-down list
    public static final String option = "option"; // Defines an option in a drop-down list
    public static final String output = "output"; // Defines the result of a calculation
    public static final String p = "p"; // Defines a paragraph
    public static final String param = "param"; // Defines a parameter for an object
    public static final String picture = "picture"; // Defines a container for multiple image resources
    public static final String pre = "pre"; // Defines preformatted text
    public static final String progress = "progress"; // Represents the progress of a task
    public static final String q = "q"; // Defines a short quotation
    public static final String rp = "rp"; // Defines what to show in browsers that do not support ruby annotations
    public static final String rt = "rt"; // Defines an explanation/pronunciation of characters (for East Asian typography)
    public static final String ruby = "ruby"; // Defines a ruby annotation (for East Asian typography)
    public static final String s = "s"; // Defines text that is no longer correct
    public static final String samp = "samp"; // Defines sample output from a computer program
    public static final String script = "script"; // Defines a client-side script
    public static final String section = "section"; // Defines a section in a document
    public static final String select = "select"; // Defines a drop-down list
    public static final String small = "small"; // Defines smaller text
    public static final String source = "source"; // Defines multiple media resources for media elements (--video-- and --audio--)
    public static final String span = "span"; // Defines a section in a document
    public static final String strike = "strike"; // Not supported in HTML5. Use --del-- or --s-- instead. Defines strikethrough text
    public static final String strong = "strong"; // Defines important text
    public static final String style = "style"; // Defines style information for a document
    public static final String sub = "sub"; // Defines subscripted text
    public static final String summary = "summary"; // Defines a visible heading for a --details-- element
    public static final String sup = "sup"; // Defines superscripted text
    public static final String svg = "svg"; // Defines a container for SVG graphics
    public static final String table = "table"; // Defines a table
    public static final String tbody = "tbody"; // Groups the body content in a table
    public static final String td = "td"; // Defines a cell in a table
    public static final String template = "template"; // Defines a template
    public static final String textarea = "textarea"; // Defines a multiline input control (text area)
    public static final String tfoot = "tfoot"; // Groups the footer content in a table
    public static final String th = "th"; // Defines a header cell in a table
    public static final String thead = "thead"; // Groups the header content in a table
    public static final String time = "time"; // Defines a date/time
    public static final String title = "title"; // Defines a title for the document
    public static final String tr = "tr"; // Defines a row in a table
    public static final String track = "track"; // Defines text tracks for media elements (--video-- and --audio--)
    public static final String tt = "tt"; // Not supported in HTML5. Use CSS instead. Defines teletype text
    public static final String u = "u"; // Defines text that should be stylistically different from normal text
    public static final String ul = "ul"; // Defines an unordered list
    public static final String var = "var"; // Defines a variable
    public static final String video = "video"; // Defines a video or movie
    public static final String wbr = "wbr"; // Defines a possible line-break
}
